name: Generate Metrics

on:
  # Run the workflow automatically at midnight (UTC) every day
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate Combined Metrics
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.combined.svg # Save output to this file
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: ""
          # Configure Habits Plugin
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          # Configure Activity Plugin
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          # Set Timezone
          config_timezone: Asia/Phnom_Penh

      # Commit Updated Metrics
      - name: Commit Metrics
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add metrics.plugin.combined.svg
          git commit -m "Update metrics"
          git push
